// ======================================================================
// \title  Stage9Clean36TopologyAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for Stage9Clean36 topology
// ======================================================================

#ifndef Stage9Clean36_Stage9Clean36TopologyAc_HPP
#define Stage9Clean36_Stage9Clean36TopologyAc_HPP

#include "Drv/BlockDriver/BlockDriver.hpp"
#include "Drv/TcpServer/TcpServer.hpp"
#include "Stage9Clean36/Top/Stage9Clean36TopologyDefs.hpp"
#include "Svc/ActiveLogger/ActiveLogger.hpp"
#include "Svc/ActiveRateGroup/ActiveRateGroup.hpp"
#include "Svc/AssertFatalAdapter/AssertFatalAdapter.hpp"
#include "Svc/BufferManager/BufferManager.hpp"
#include "Svc/ChronoTime/ChronoTime.hpp"
#include "Svc/CmdDispatcher/CommandDispatcher.hpp"
#include "Svc/CmdSequencer/CmdSequencer.hpp"
#include "Svc/ComQueue/ComQueue.hpp"
#include "Svc/ComStub/ComStub.hpp"
#include "Svc/Deframer/Deframer.hpp"
#include "Svc/FatalHandler/FatalHandler.hpp"
#include "Svc/FileDownlink/FileDownlink.hpp"
#include "Svc/FileManager/FileManager.hpp"
#include "Svc/FileUplink/FileUplink.hpp"
#include "Svc/Framer/Framer.hpp"
#include "Svc/Health/Health.hpp"
#include "Svc/PassiveConsoleTextLogger/PassiveTextLogger.hpp"
#include "Svc/PrmDb/PrmDb.hpp"
#include "Svc/RateGroupDriver/RateGroupDriver.hpp"
#include "Svc/SystemResources/SystemResources.hpp"
#include "Svc/TlmChan/TlmChan.hpp"

// ----------------------------------------------------------------------
// Component instances
// ----------------------------------------------------------------------

namespace Stage9Clean36 {

  //! blockDrv
  extern Drv::BlockDriver blockDrv;

}

namespace Stage9Clean36 {

  //! bufferManager
  extern Svc::BufferManager bufferManager;

}

namespace Stage9Clean36 {

  //! chronoTime
  extern Svc::ChronoTime chronoTime;

}

namespace Stage9Clean36 {

  //! cmdDisp
  extern Svc::CommandDispatcher cmdDisp;

}

namespace Stage9Clean36 {

  //! cmdSeq
  extern Svc::CmdSequencer cmdSeq;

}

namespace Stage9Clean36 {

  //! comDriver
  extern Drv::TcpServer comDriver;

}

namespace Stage9Clean36 {

  //! comQueue
  extern Svc::ComQueue comQueue;

}

namespace Stage9Clean36 {

  //! comStub
  extern Svc::ComStub comStub;

}

namespace Stage9Clean36 {

  //! deframer
  extern Svc::Deframer deframer;

}

namespace Stage9Clean36 {

  //! eventLogger
  extern Svc::ActiveLogger eventLogger;

}

namespace Stage9Clean36 {

  //! fatalAdapter
  extern Svc::AssertFatalAdapter fatalAdapter;

}

namespace Stage9Clean36 {

  //! fatalHandler
  extern Svc::FatalHandler fatalHandler;

}

namespace Stage9Clean36 {

  //! fileDownlink
  extern Svc::FileDownlink fileDownlink;

}

namespace Stage9Clean36 {

  //! fileManager
  extern Svc::FileManager fileManager;

}

namespace Stage9Clean36 {

  //! fileUplink
  extern Svc::FileUplink fileUplink;

}

namespace Stage9Clean36 {

  //! framer
  extern Svc::Framer framer;

}

namespace Stage9Clean36 {

  //! health
  extern Svc::Health health;

}

namespace Stage9Clean36 {

  //! prmDb
  extern Svc::PrmDb prmDb;

}

namespace Stage9Clean36 {

  //! rateGroup1
  extern Svc::ActiveRateGroup rateGroup1;

}

namespace Stage9Clean36 {

  //! rateGroup2
  extern Svc::ActiveRateGroup rateGroup2;

}

namespace Stage9Clean36 {

  //! rateGroup3
  extern Svc::ActiveRateGroup rateGroup3;

}

namespace Stage9Clean36 {

  //! rateGroupDriver
  extern Svc::RateGroupDriver rateGroupDriver;

}

namespace Stage9Clean36 {

  //! systemResources
  extern Svc::SystemResources systemResources;

}

namespace Stage9Clean36 {

  //! textLogger
  extern Svc::PassiveTextLogger textLogger;

}

namespace Stage9Clean36 {

  //! tlmSend
  extern Svc::TlmChan tlmSend;

}

namespace Stage9Clean36 {

  // ----------------------------------------------------------------------
  // Constants
  // ----------------------------------------------------------------------

  namespace BaseIds {
    enum {
      Stage9Clean36_blockDrv = 0x100,
      Stage9Clean36_rateGroup1 = 0x200,
      Stage9Clean36_rateGroup2 = 0x300,
      Stage9Clean36_rateGroup3 = 0x400,
      Stage9Clean36_cmdDisp = 0x500,
      Stage9Clean36_cmdSeq = 0x600,
      Stage9Clean36_comQueue = 0x700,
      Stage9Clean36_fileDownlink = 0x800,
      Stage9Clean36_fileManager = 0x900,
      Stage9Clean36_fileUplink = 0xA00,
      Stage9Clean36_eventLogger = 0xB00,
      Stage9Clean36_tlmSend = 0xC00,
      Stage9Clean36_prmDb = 0xD00,
      Stage9Clean36_health = 0x2000,
      Stage9Clean36_comDriver = 0x4000,
      Stage9Clean36_framer = 0x4100,
      Stage9Clean36_fatalAdapter = 0x4200,
      Stage9Clean36_fatalHandler = 0x4300,
      Stage9Clean36_bufferManager = 0x4400,
      Stage9Clean36_chronoTime = 0x4500,
      Stage9Clean36_rateGroupDriver = 0x4600,
      Stage9Clean36_textLogger = 0x4800,
      Stage9Clean36_deframer = 0x4900,
      Stage9Clean36_systemResources = 0x4A00,
      Stage9Clean36_comStub = 0x4B00,
    };
  }

  namespace InstanceIds {
    enum {
      Stage9Clean36_blockDrv,
      Stage9Clean36_bufferManager,
      Stage9Clean36_chronoTime,
      Stage9Clean36_cmdDisp,
      Stage9Clean36_cmdSeq,
      Stage9Clean36_comDriver,
      Stage9Clean36_comQueue,
      Stage9Clean36_comStub,
      Stage9Clean36_deframer,
      Stage9Clean36_eventLogger,
      Stage9Clean36_fatalAdapter,
      Stage9Clean36_fatalHandler,
      Stage9Clean36_fileDownlink,
      Stage9Clean36_fileManager,
      Stage9Clean36_fileUplink,
      Stage9Clean36_framer,
      Stage9Clean36_health,
      Stage9Clean36_prmDb,
      Stage9Clean36_rateGroup1,
      Stage9Clean36_rateGroup2,
      Stage9Clean36_rateGroup3,
      Stage9Clean36_rateGroupDriver,
      Stage9Clean36_systemResources,
      Stage9Clean36_textLogger,
      Stage9Clean36_tlmSend,
    };
  }

  namespace Priorities {
    enum {
      Stage9Clean36_blockDrv = 140,
      Stage9Clean36_cmdDisp = 101,
      Stage9Clean36_cmdSeq = 100,
      Stage9Clean36_comQueue = 100,
      Stage9Clean36_eventLogger = 98,
      Stage9Clean36_fileDownlink = 100,
      Stage9Clean36_fileManager = 100,
      Stage9Clean36_fileUplink = 100,
      Stage9Clean36_prmDb = 96,
      Stage9Clean36_rateGroup1 = 120,
      Stage9Clean36_rateGroup2 = 119,
      Stage9Clean36_rateGroup3 = 118,
      Stage9Clean36_tlmSend = 97,
    };
  }

  namespace QueueSizes {
    enum {
      Stage9Clean36_blockDrv = 10,
      Stage9Clean36_cmdDisp = 20,
      Stage9Clean36_cmdSeq = 10,
      Stage9Clean36_comQueue = 10,
      Stage9Clean36_eventLogger = 10,
      Stage9Clean36_fileDownlink = 30,
      Stage9Clean36_fileManager = 30,
      Stage9Clean36_fileUplink = 30,
      Stage9Clean36_health = 25,
      Stage9Clean36_prmDb = 10,
      Stage9Clean36_rateGroup1 = 10,
      Stage9Clean36_rateGroup2 = 10,
      Stage9Clean36_rateGroup3 = 10,
      Stage9Clean36_tlmSend = 10,
    };
  }

  namespace StackSizes {
    enum {
      Stage9Clean36_blockDrv = 65536,
      Stage9Clean36_cmdDisp = 65536,
      Stage9Clean36_cmdSeq = 65536,
      Stage9Clean36_comQueue = 65536,
      Stage9Clean36_eventLogger = 65536,
      Stage9Clean36_fileDownlink = 65536,
      Stage9Clean36_fileManager = 65536,
      Stage9Clean36_fileUplink = 65536,
      Stage9Clean36_prmDb = 65536,
      Stage9Clean36_rateGroup1 = 65536,
      Stage9Clean36_rateGroup2 = 65536,
      Stage9Clean36_rateGroup3 = 65536,
      Stage9Clean36_tlmSend = 65536,
    };
  }

  namespace TaskIds {
    enum {
      Stage9Clean36_blockDrv,
      Stage9Clean36_cmdDisp,
      Stage9Clean36_cmdSeq,
      Stage9Clean36_comQueue,
      Stage9Clean36_eventLogger,
      Stage9Clean36_fileDownlink,
      Stage9Clean36_fileManager,
      Stage9Clean36_fileUplink,
      Stage9Clean36_prmDb,
      Stage9Clean36_rateGroup1,
      Stage9Clean36_rateGroup2,
      Stage9Clean36_rateGroup3,
      Stage9Clean36_tlmSend,
    };
  }

  // ----------------------------------------------------------------------
  // Component configuration objects
  // ----------------------------------------------------------------------

  namespace ConfigObjects {

    namespace Stage9Clean36_health {
      //!< Number of entries in the pingEntryies array
      constexpr FwSizeType NUM_PING_ENTRIES = 12;
      //!< Ping entry configuration for Svc::Health
      extern Svc::Health::PingEntry pingEntries[NUM_PING_ENTRIES];
    }

  }

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  //! Initialize components
  void initComponents(
      const TopologyState& state //!< The topology state
  );

  //! Configure components
  void configComponents(
      const TopologyState& state //!< The topology state
  );

  //! Set component base Ids
  void setBaseIds();

  //! Connect components
  void connectComponents();

  //! Register commands
  void regCommands();

  //! Read parameters
  void readParameters();

  //! Load parameters
  void loadParameters();

  //! Start tasks
  void startTasks(
      const TopologyState& state //!< The topology state
  );

  //! Stop tasks
  void stopTasks(
      const TopologyState& state //!< The topology state
  );

  //! Free threads
  void freeThreads(
      const TopologyState& state //!< The topology state
  );

  //! Tear down components
  void tearDownComponents(
      const TopologyState& state //!< The topology state
  );

  // ----------------------------------------------------------------------
  // Setup and teardown functions
  // ----------------------------------------------------------------------

  //! Set up the topology
  void setup(
      const TopologyState& state //!< The topology state
  );

  //! Tear down the topology
  void teardown(
      const TopologyState& state //!< The topology state
  );

}

#endif
