// ======================================================================
// \title  Stage9Clean36TopologyAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for Stage9Clean36 topology
// ======================================================================

#include "Stage9Clean36/Top/Stage9Clean36TopologyAc.hpp"

// ----------------------------------------------------------------------
// Component instances
// ----------------------------------------------------------------------

namespace Stage9Clean36 {

  Drv::BlockDriver blockDrv(FW_OPTIONAL_NAME("blockDrv"));

}

namespace Stage9Clean36 {

  Svc::BufferManager bufferManager(FW_OPTIONAL_NAME("bufferManager"));

}

namespace Stage9Clean36 {

  Svc::ChronoTime chronoTime(FW_OPTIONAL_NAME("chronoTime"));

}

namespace Stage9Clean36 {

  Svc::CommandDispatcher cmdDisp(FW_OPTIONAL_NAME("cmdDisp"));

}

namespace Stage9Clean36 {

  Svc::CmdSequencer cmdSeq(FW_OPTIONAL_NAME("cmdSeq"));

}

namespace Stage9Clean36 {

  Drv::TcpServer comDriver(FW_OPTIONAL_NAME("comDriver"));

}

namespace Stage9Clean36 {

  Svc::ComQueue comQueue(FW_OPTIONAL_NAME("comQueue"));

}

namespace Stage9Clean36 {

  Svc::ComStub comStub(FW_OPTIONAL_NAME("comStub"));

}

namespace Stage9Clean36 {

  Svc::Deframer deframer(FW_OPTIONAL_NAME("deframer"));

}

namespace Stage9Clean36 {

  Svc::ActiveLogger eventLogger(FW_OPTIONAL_NAME("eventLogger"));

}

namespace Stage9Clean36 {

  Svc::AssertFatalAdapter fatalAdapter(FW_OPTIONAL_NAME("fatalAdapter"));

}

namespace Stage9Clean36 {

  Svc::FatalHandler fatalHandler(FW_OPTIONAL_NAME("fatalHandler"));

}

namespace Stage9Clean36 {

  Svc::FileDownlink fileDownlink(FW_OPTIONAL_NAME("fileDownlink"));

}

namespace Stage9Clean36 {

  Svc::FileManager fileManager(FW_OPTIONAL_NAME("fileManager"));

}

namespace Stage9Clean36 {

  Svc::FileUplink fileUplink(FW_OPTIONAL_NAME("fileUplink"));

}

namespace Stage9Clean36 {

  Svc::Framer framer(FW_OPTIONAL_NAME("framer"));

}

namespace Stage9Clean36 {

  Svc::Health health(FW_OPTIONAL_NAME("health"));

}

namespace Stage9Clean36 {

  Svc::PrmDb prmDb(FW_OPTIONAL_NAME("prmDb"));

}

namespace Stage9Clean36 {

  Svc::ActiveRateGroup rateGroup1(FW_OPTIONAL_NAME("rateGroup1"));

}

namespace Stage9Clean36 {

  Svc::ActiveRateGroup rateGroup2(FW_OPTIONAL_NAME("rateGroup2"));

}

namespace Stage9Clean36 {

  Svc::ActiveRateGroup rateGroup3(FW_OPTIONAL_NAME("rateGroup3"));

}

namespace Stage9Clean36 {

  Svc::RateGroupDriver rateGroupDriver(FW_OPTIONAL_NAME("rateGroupDriver"));

}

namespace Stage9Clean36 {

  Svc::SystemResources systemResources(FW_OPTIONAL_NAME("systemResources"));

}

namespace Stage9Clean36 {

  Svc::PassiveTextLogger textLogger(FW_OPTIONAL_NAME("textLogger"));

}

namespace Stage9Clean36 {

  Svc::TlmChan tlmSend(FW_OPTIONAL_NAME("tlmSend"));

}

namespace Stage9Clean36 {


  // ----------------------------------------------------------------------
  // Component configuration objects
  // ----------------------------------------------------------------------

  namespace ConfigObjects {

    namespace Stage9Clean36_health {
      Svc::Health::PingEntry pingEntries[NUM_PING_ENTRIES] = {
        {
          PingEntries::Stage9Clean36_blockDrv::WARN,
          PingEntries::Stage9Clean36_blockDrv::FATAL,
          "Stage9Clean36_blockDrv"
        },
        {
          PingEntries::Stage9Clean36_cmdDisp::WARN,
          PingEntries::Stage9Clean36_cmdDisp::FATAL,
          "Stage9Clean36_cmdDisp"
        },
        {
          PingEntries::Stage9Clean36_cmdSeq::WARN,
          PingEntries::Stage9Clean36_cmdSeq::FATAL,
          "Stage9Clean36_cmdSeq"
        },
        {
          PingEntries::Stage9Clean36_eventLogger::WARN,
          PingEntries::Stage9Clean36_eventLogger::FATAL,
          "Stage9Clean36_eventLogger"
        },
        {
          PingEntries::Stage9Clean36_fileDownlink::WARN,
          PingEntries::Stage9Clean36_fileDownlink::FATAL,
          "Stage9Clean36_fileDownlink"
        },
        {
          PingEntries::Stage9Clean36_fileManager::WARN,
          PingEntries::Stage9Clean36_fileManager::FATAL,
          "Stage9Clean36_fileManager"
        },
        {
          PingEntries::Stage9Clean36_fileUplink::WARN,
          PingEntries::Stage9Clean36_fileUplink::FATAL,
          "Stage9Clean36_fileUplink"
        },
        {
          PingEntries::Stage9Clean36_prmDb::WARN,
          PingEntries::Stage9Clean36_prmDb::FATAL,
          "Stage9Clean36_prmDb"
        },
        {
          PingEntries::Stage9Clean36_rateGroup1::WARN,
          PingEntries::Stage9Clean36_rateGroup1::FATAL,
          "Stage9Clean36_rateGroup1"
        },
        {
          PingEntries::Stage9Clean36_rateGroup2::WARN,
          PingEntries::Stage9Clean36_rateGroup2::FATAL,
          "Stage9Clean36_rateGroup2"
        },
        {
          PingEntries::Stage9Clean36_rateGroup3::WARN,
          PingEntries::Stage9Clean36_rateGroup3::FATAL,
          "Stage9Clean36_rateGroup3"
        },
        {
          PingEntries::Stage9Clean36_tlmSend::WARN,
          PingEntries::Stage9Clean36_tlmSend::FATAL,
          "Stage9Clean36_tlmSend"
        },
      };
    }

  }


  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void initComponents(const TopologyState& state) {
    Stage9Clean36::blockDrv.init(QueueSizes::Stage9Clean36_blockDrv, InstanceIds::Stage9Clean36_blockDrv);
    Stage9Clean36::bufferManager.init(InstanceIds::Stage9Clean36_bufferManager);
    Stage9Clean36::chronoTime.init(InstanceIds::Stage9Clean36_chronoTime);
    Stage9Clean36::cmdDisp.init(QueueSizes::Stage9Clean36_cmdDisp, InstanceIds::Stage9Clean36_cmdDisp);
    Stage9Clean36::cmdSeq.init(QueueSizes::Stage9Clean36_cmdSeq, InstanceIds::Stage9Clean36_cmdSeq);
    Stage9Clean36::comDriver.init(InstanceIds::Stage9Clean36_comDriver);
    Stage9Clean36::comQueue.init(QueueSizes::Stage9Clean36_comQueue, InstanceIds::Stage9Clean36_comQueue);
    Stage9Clean36::comStub.init(InstanceIds::Stage9Clean36_comStub);
    Stage9Clean36::deframer.init(InstanceIds::Stage9Clean36_deframer);
    Stage9Clean36::eventLogger.init(QueueSizes::Stage9Clean36_eventLogger, InstanceIds::Stage9Clean36_eventLogger);
    Stage9Clean36::fatalAdapter.init(InstanceIds::Stage9Clean36_fatalAdapter);
    Stage9Clean36::fatalHandler.init(InstanceIds::Stage9Clean36_fatalHandler);
    Stage9Clean36::fileDownlink.init(QueueSizes::Stage9Clean36_fileDownlink, InstanceIds::Stage9Clean36_fileDownlink);
    Stage9Clean36::fileManager.init(QueueSizes::Stage9Clean36_fileManager, InstanceIds::Stage9Clean36_fileManager);
    Stage9Clean36::fileUplink.init(QueueSizes::Stage9Clean36_fileUplink, InstanceIds::Stage9Clean36_fileUplink);
    Stage9Clean36::framer.init(InstanceIds::Stage9Clean36_framer);
    Stage9Clean36::health.init(QueueSizes::Stage9Clean36_health, InstanceIds::Stage9Clean36_health);
    Stage9Clean36::prmDb.init(QueueSizes::Stage9Clean36_prmDb, InstanceIds::Stage9Clean36_prmDb);
    Stage9Clean36::rateGroup1.init(QueueSizes::Stage9Clean36_rateGroup1, InstanceIds::Stage9Clean36_rateGroup1);
    Stage9Clean36::rateGroup2.init(QueueSizes::Stage9Clean36_rateGroup2, InstanceIds::Stage9Clean36_rateGroup2);
    Stage9Clean36::rateGroup3.init(QueueSizes::Stage9Clean36_rateGroup3, InstanceIds::Stage9Clean36_rateGroup3);
    Stage9Clean36::rateGroupDriver.init(InstanceIds::Stage9Clean36_rateGroupDriver);
    Stage9Clean36::systemResources.init(InstanceIds::Stage9Clean36_systemResources);
    Stage9Clean36::textLogger.init(InstanceIds::Stage9Clean36_textLogger);
    Stage9Clean36::tlmSend.init(QueueSizes::Stage9Clean36_tlmSend, InstanceIds::Stage9Clean36_tlmSend);
  }

  void configComponents(const TopologyState& state) {
    // Nothing to do
  }

  void setBaseIds() {
    Stage9Clean36::blockDrv.setIdBase(BaseIds::Stage9Clean36_blockDrv);
    Stage9Clean36::rateGroup1.setIdBase(BaseIds::Stage9Clean36_rateGroup1);
    Stage9Clean36::rateGroup2.setIdBase(BaseIds::Stage9Clean36_rateGroup2);
    Stage9Clean36::rateGroup3.setIdBase(BaseIds::Stage9Clean36_rateGroup3);
    Stage9Clean36::cmdDisp.setIdBase(BaseIds::Stage9Clean36_cmdDisp);
    Stage9Clean36::cmdSeq.setIdBase(BaseIds::Stage9Clean36_cmdSeq);
    Stage9Clean36::comQueue.setIdBase(BaseIds::Stage9Clean36_comQueue);
    Stage9Clean36::fileDownlink.setIdBase(BaseIds::Stage9Clean36_fileDownlink);
    Stage9Clean36::fileManager.setIdBase(BaseIds::Stage9Clean36_fileManager);
    Stage9Clean36::fileUplink.setIdBase(BaseIds::Stage9Clean36_fileUplink);
    Stage9Clean36::eventLogger.setIdBase(BaseIds::Stage9Clean36_eventLogger);
    Stage9Clean36::tlmSend.setIdBase(BaseIds::Stage9Clean36_tlmSend);
    Stage9Clean36::prmDb.setIdBase(BaseIds::Stage9Clean36_prmDb);
    Stage9Clean36::health.setIdBase(BaseIds::Stage9Clean36_health);
    Stage9Clean36::comDriver.setIdBase(BaseIds::Stage9Clean36_comDriver);
    Stage9Clean36::framer.setIdBase(BaseIds::Stage9Clean36_framer);
    Stage9Clean36::fatalAdapter.setIdBase(BaseIds::Stage9Clean36_fatalAdapter);
    Stage9Clean36::fatalHandler.setIdBase(BaseIds::Stage9Clean36_fatalHandler);
    Stage9Clean36::bufferManager.setIdBase(BaseIds::Stage9Clean36_bufferManager);
    Stage9Clean36::chronoTime.setIdBase(BaseIds::Stage9Clean36_chronoTime);
    Stage9Clean36::rateGroupDriver.setIdBase(BaseIds::Stage9Clean36_rateGroupDriver);
    Stage9Clean36::textLogger.setIdBase(BaseIds::Stage9Clean36_textLogger);
    Stage9Clean36::deframer.setIdBase(BaseIds::Stage9Clean36_deframer);
    Stage9Clean36::systemResources.setIdBase(BaseIds::Stage9Clean36_systemResources);
    Stage9Clean36::comStub.setIdBase(BaseIds::Stage9Clean36_comStub);
  }

  void connectComponents() {

    // Command
    Stage9Clean36::cmdDisp.set_compCmdSend_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_CmdDisp_InputPort(0)
    );
    Stage9Clean36::cmdDisp.set_compCmdSend_OutputPort(
        1,
        Stage9Clean36::cmdSeq.get_cmdIn_InputPort(0)
    );
    Stage9Clean36::cmdDisp.set_compCmdSend_OutputPort(
        2,
        Stage9Clean36::eventLogger.get_CmdDisp_InputPort(0)
    );
    Stage9Clean36::cmdDisp.set_compCmdSend_OutputPort(
        3,
        Stage9Clean36::fileDownlink.get_cmdIn_InputPort(0)
    );
    Stage9Clean36::cmdDisp.set_compCmdSend_OutputPort(
        4,
        Stage9Clean36::fileManager.get_cmdIn_InputPort(0)
    );
    Stage9Clean36::cmdDisp.set_compCmdSend_OutputPort(
        5,
        Stage9Clean36::health.get_CmdDisp_InputPort(0)
    );
    Stage9Clean36::cmdDisp.set_compCmdSend_OutputPort(
        6,
        Stage9Clean36::prmDb.get_CmdDisp_InputPort(0)
    );
    Stage9Clean36::cmdDisp.set_compCmdSend_OutputPort(
        7,
        Stage9Clean36::systemResources.get_CmdDisp_InputPort(0)
    );

    // CommandRegistration
    Stage9Clean36::cmdDisp.set_CmdReg_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdReg_InputPort(0)
    );
    Stage9Clean36::cmdSeq.set_cmdRegOut_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdReg_InputPort(1)
    );
    Stage9Clean36::eventLogger.set_CmdReg_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdReg_InputPort(2)
    );
    Stage9Clean36::fileDownlink.set_cmdRegOut_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdReg_InputPort(3)
    );
    Stage9Clean36::fileManager.set_cmdRegOut_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdReg_InputPort(4)
    );
    Stage9Clean36::health.set_CmdReg_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdReg_InputPort(5)
    );
    Stage9Clean36::prmDb.set_CmdReg_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdReg_InputPort(6)
    );
    Stage9Clean36::systemResources.set_CmdReg_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdReg_InputPort(7)
    );

    // CommandResponse
    Stage9Clean36::cmdDisp.set_CmdStatus_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdStat_InputPort(0)
    );
    Stage9Clean36::cmdSeq.set_cmdResponseOut_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdStat_InputPort(0)
    );
    Stage9Clean36::eventLogger.set_CmdStatus_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdStat_InputPort(0)
    );
    Stage9Clean36::fileDownlink.set_cmdResponseOut_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdStat_InputPort(0)
    );
    Stage9Clean36::fileManager.set_cmdResponseOut_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdStat_InputPort(0)
    );
    Stage9Clean36::health.set_CmdStatus_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdStat_InputPort(0)
    );
    Stage9Clean36::prmDb.set_CmdStatus_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdStat_InputPort(0)
    );
    Stage9Clean36::systemResources.set_CmdStatus_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_compCmdStat_InputPort(0)
    );

    // Downlink
    Stage9Clean36::comDriver.set_deallocate_OutputPort(
        0,
        Stage9Clean36::bufferManager.get_bufferSendIn_InputPort(0)
    );
    Stage9Clean36::comDriver.set_ready_OutputPort(
        0,
        Stage9Clean36::comStub.get_drvConnected_InputPort(0)
    );
    Stage9Clean36::comQueue.set_buffQueueSend_OutputPort(
        0,
        Stage9Clean36::framer.get_bufferIn_InputPort(0)
    );
    Stage9Clean36::comQueue.set_comQueueSend_OutputPort(
        0,
        Stage9Clean36::framer.get_comIn_InputPort(0)
    );
    Stage9Clean36::comStub.set_comStatus_OutputPort(
        0,
        Stage9Clean36::framer.get_comStatusIn_InputPort(0)
    );
    Stage9Clean36::comStub.set_drvDataOut_OutputPort(
        0,
        Stage9Clean36::comDriver.get_send_InputPort(0)
    );
    Stage9Clean36::eventLogger.set_PktSend_OutputPort(
        0,
        Stage9Clean36::comQueue.get_comQueueIn_InputPort(0)
    );
    Stage9Clean36::fileDownlink.set_bufferSendOut_OutputPort(
        0,
        Stage9Clean36::comQueue.get_buffQueueIn_InputPort(0)
    );
    Stage9Clean36::framer.set_bufferDeallocate_OutputPort(
        0,
        Stage9Clean36::fileDownlink.get_bufferReturn_InputPort(0)
    );
    Stage9Clean36::framer.set_comStatusOut_OutputPort(
        0,
        Stage9Clean36::comQueue.get_comStatusIn_InputPort(0)
    );
    Stage9Clean36::framer.set_framedAllocate_OutputPort(
        0,
        Stage9Clean36::bufferManager.get_bufferGetCallee_InputPort(0)
    );
    Stage9Clean36::framer.set_framedOut_OutputPort(
        0,
        Stage9Clean36::comStub.get_comDataIn_InputPort(0)
    );
    Stage9Clean36::tlmSend.set_PktSend_OutputPort(
        0,
        Stage9Clean36::comQueue.get_comQueueIn_InputPort(1)
    );

    // Events
    Stage9Clean36::bufferManager.set_eventOut_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::cmdDisp.set_Log_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::cmdSeq.set_logOut_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::comQueue.set_Log_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::eventLogger.set_Log_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::fatalAdapter.set_Log_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::fileDownlink.set_eventOut_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::fileManager.set_eventOut_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::fileUplink.set_eventOut_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::health.set_Log_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::prmDb.set_Log_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::rateGroup1.set_Log_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::rateGroup2.set_Log_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::rateGroup3.set_Log_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );
    Stage9Clean36::systemResources.set_Log_OutputPort(
        0,
        Stage9Clean36::eventLogger.get_LogRecv_InputPort(0)
    );

    // FaultProtection
    Stage9Clean36::eventLogger.set_FatalAnnounce_OutputPort(
        0,
        Stage9Clean36::fatalHandler.get_FatalReceive_InputPort(0)
    );

    // Health
    Stage9Clean36::blockDrv.set_PingOut_OutputPort(
        0,
        Stage9Clean36::health.get_PingReturn_InputPort(0)
    );
    Stage9Clean36::cmdDisp.set_pingOut_OutputPort(
        0,
        Stage9Clean36::health.get_PingReturn_InputPort(1)
    );
    Stage9Clean36::cmdSeq.set_pingOut_OutputPort(
        0,
        Stage9Clean36::health.get_PingReturn_InputPort(2)
    );
    Stage9Clean36::eventLogger.set_pingOut_OutputPort(
        0,
        Stage9Clean36::health.get_PingReturn_InputPort(3)
    );
    Stage9Clean36::fileDownlink.set_pingOut_OutputPort(
        0,
        Stage9Clean36::health.get_PingReturn_InputPort(4)
    );
    Stage9Clean36::fileManager.set_pingOut_OutputPort(
        0,
        Stage9Clean36::health.get_PingReturn_InputPort(5)
    );
    Stage9Clean36::fileUplink.set_pingOut_OutputPort(
        0,
        Stage9Clean36::health.get_PingReturn_InputPort(6)
    );
    Stage9Clean36::health.set_PingSend_OutputPort(
        0,
        Stage9Clean36::blockDrv.get_PingIn_InputPort(0)
    );
    Stage9Clean36::health.set_PingSend_OutputPort(
        1,
        Stage9Clean36::cmdDisp.get_pingIn_InputPort(0)
    );
    Stage9Clean36::health.set_PingSend_OutputPort(
        2,
        Stage9Clean36::cmdSeq.get_pingIn_InputPort(0)
    );
    Stage9Clean36::health.set_PingSend_OutputPort(
        3,
        Stage9Clean36::eventLogger.get_pingIn_InputPort(0)
    );
    Stage9Clean36::health.set_PingSend_OutputPort(
        4,
        Stage9Clean36::fileDownlink.get_pingIn_InputPort(0)
    );
    Stage9Clean36::health.set_PingSend_OutputPort(
        5,
        Stage9Clean36::fileManager.get_pingIn_InputPort(0)
    );
    Stage9Clean36::health.set_PingSend_OutputPort(
        6,
        Stage9Clean36::fileUplink.get_pingIn_InputPort(0)
    );
    Stage9Clean36::health.set_PingSend_OutputPort(
        7,
        Stage9Clean36::prmDb.get_pingIn_InputPort(0)
    );
    Stage9Clean36::health.set_PingSend_OutputPort(
        8,
        Stage9Clean36::rateGroup1.get_PingIn_InputPort(0)
    );
    Stage9Clean36::health.set_PingSend_OutputPort(
        9,
        Stage9Clean36::rateGroup2.get_PingIn_InputPort(0)
    );
    Stage9Clean36::health.set_PingSend_OutputPort(
        10,
        Stage9Clean36::rateGroup3.get_PingIn_InputPort(0)
    );
    Stage9Clean36::health.set_PingSend_OutputPort(
        11,
        Stage9Clean36::tlmSend.get_pingIn_InputPort(0)
    );
    Stage9Clean36::prmDb.set_pingOut_OutputPort(
        0,
        Stage9Clean36::health.get_PingReturn_InputPort(7)
    );
    Stage9Clean36::rateGroup1.set_PingOut_OutputPort(
        0,
        Stage9Clean36::health.get_PingReturn_InputPort(8)
    );
    Stage9Clean36::rateGroup2.set_PingOut_OutputPort(
        0,
        Stage9Clean36::health.get_PingReturn_InputPort(9)
    );
    Stage9Clean36::rateGroup3.set_PingOut_OutputPort(
        0,
        Stage9Clean36::health.get_PingReturn_InputPort(10)
    );
    Stage9Clean36::tlmSend.set_pingOut_OutputPort(
        0,
        Stage9Clean36::health.get_PingReturn_InputPort(11)
    );

    // RateGroups
    Stage9Clean36::blockDrv.set_CycleOut_OutputPort(
        0,
        Stage9Clean36::rateGroupDriver.get_CycleIn_InputPort(0)
    );
    Stage9Clean36::rateGroup1.set_RateGroupMemberOut_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_Run_InputPort(0)
    );
    Stage9Clean36::rateGroup1.set_RateGroupMemberOut_OutputPort(
        1,
        Stage9Clean36::fileDownlink.get_Run_InputPort(0)
    );
    Stage9Clean36::rateGroup1.set_RateGroupMemberOut_OutputPort(
        2,
        Stage9Clean36::systemResources.get_run_InputPort(0)
    );
    Stage9Clean36::rateGroup2.set_RateGroupMemberOut_OutputPort(
        0,
        Stage9Clean36::cmdSeq.get_schedIn_InputPort(0)
    );
    Stage9Clean36::rateGroup3.set_RateGroupMemberOut_OutputPort(
        0,
        Stage9Clean36::health.get_Run_InputPort(0)
    );
    Stage9Clean36::rateGroup3.set_RateGroupMemberOut_OutputPort(
        1,
        Stage9Clean36::blockDrv.get_Sched_InputPort(0)
    );
    Stage9Clean36::rateGroup3.set_RateGroupMemberOut_OutputPort(
        2,
        Stage9Clean36::bufferManager.get_schedIn_InputPort(0)
    );
    Stage9Clean36::rateGroupDriver.set_CycleOut_OutputPort(
        0,
        Stage9Clean36::rateGroup1.get_CycleIn_InputPort(0)
    );
    Stage9Clean36::rateGroupDriver.set_CycleOut_OutputPort(
        1,
        Stage9Clean36::rateGroup2.get_CycleIn_InputPort(0)
    );
    Stage9Clean36::rateGroupDriver.set_CycleOut_OutputPort(
        2,
        Stage9Clean36::rateGroup3.get_CycleIn_InputPort(0)
    );

    // Sequencer
    Stage9Clean36::cmdDisp.set_seqCmdStatus_OutputPort(
        0,
        Stage9Clean36::cmdSeq.get_cmdResponseIn_InputPort(0)
    );
    Stage9Clean36::cmdSeq.set_comCmdOut_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_seqCmdBuff_InputPort(0)
    );

    // Telemetry
    Stage9Clean36::blockDrv.set_Tlm_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );
    Stage9Clean36::bufferManager.set_tlmOut_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );
    Stage9Clean36::cmdDisp.set_Tlm_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );
    Stage9Clean36::cmdSeq.set_tlmOut_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );
    Stage9Clean36::comQueue.set_Tlm_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );
    Stage9Clean36::fileDownlink.set_tlmOut_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );
    Stage9Clean36::fileManager.set_tlmOut_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );
    Stage9Clean36::fileUplink.set_tlmOut_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );
    Stage9Clean36::health.set_Tlm_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );
    Stage9Clean36::rateGroup1.set_Tlm_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );
    Stage9Clean36::rateGroup2.set_Tlm_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );
    Stage9Clean36::rateGroup3.set_Tlm_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );
    Stage9Clean36::systemResources.set_Tlm_OutputPort(
        0,
        Stage9Clean36::tlmSend.get_TlmRecv_InputPort(0)
    );

    // TextEvents
    Stage9Clean36::bufferManager.set_textEventOut_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::cmdDisp.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::cmdSeq.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::comQueue.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::eventLogger.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::fatalAdapter.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::fileDownlink.set_textEventOut_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::fileManager.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::fileUplink.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::health.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::prmDb.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::rateGroup1.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::rateGroup2.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::rateGroup3.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );
    Stage9Clean36::systemResources.set_LogText_OutputPort(
        0,
        Stage9Clean36::textLogger.get_TextLogger_InputPort(0)
    );

    // Time
    Stage9Clean36::blockDrv.set_Time_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::bufferManager.set_timeCaller_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::cmdDisp.set_Time_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::cmdSeq.set_timeCaller_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::comQueue.set_Time_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::eventLogger.set_Time_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::fatalAdapter.set_Time_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::fileDownlink.set_timeCaller_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::fileManager.set_timeCaller_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::fileUplink.set_timeCaller_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::health.set_Time_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::prmDb.set_Time_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::rateGroup1.set_Time_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::rateGroup2.set_Time_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::rateGroup3.set_Time_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );
    Stage9Clean36::systemResources.set_Time_OutputPort(
        0,
        Stage9Clean36::chronoTime.get_timeGetPort_InputPort(0)
    );

    // Uplink
    Stage9Clean36::cmdDisp.set_seqCmdStatus_OutputPort(
        1,
        Stage9Clean36::deframer.get_cmdResponseIn_InputPort(0)
    );
    Stage9Clean36::comDriver.set_allocate_OutputPort(
        0,
        Stage9Clean36::bufferManager.get_bufferGetCallee_InputPort(0)
    );
    Stage9Clean36::comDriver.set_recv_OutputPort(
        0,
        Stage9Clean36::comStub.get_drvDataIn_InputPort(0)
    );
    Stage9Clean36::comStub.set_comDataOut_OutputPort(
        0,
        Stage9Clean36::deframer.get_framedIn_InputPort(0)
    );
    Stage9Clean36::deframer.set_bufferAllocate_OutputPort(
        0,
        Stage9Clean36::bufferManager.get_bufferGetCallee_InputPort(0)
    );
    Stage9Clean36::deframer.set_bufferDeallocate_OutputPort(
        0,
        Stage9Clean36::bufferManager.get_bufferSendIn_InputPort(0)
    );
    Stage9Clean36::deframer.set_bufferOut_OutputPort(
        0,
        Stage9Clean36::fileUplink.get_bufferSendIn_InputPort(0)
    );
    Stage9Clean36::deframer.set_comOut_OutputPort(
        0,
        Stage9Clean36::cmdDisp.get_seqCmdBuff_InputPort(1)
    );
    Stage9Clean36::deframer.set_framedDeallocate_OutputPort(
        0,
        Stage9Clean36::bufferManager.get_bufferSendIn_InputPort(0)
    );
    Stage9Clean36::fileUplink.set_bufferSendOut_OutputPort(
        0,
        Stage9Clean36::bufferManager.get_bufferSendIn_InputPort(0)
    );
  }

  void regCommands() {
    Stage9Clean36::cmdDisp.regCommands();
    Stage9Clean36::cmdSeq.regCommands();
    Stage9Clean36::eventLogger.regCommands();
    Stage9Clean36::fileDownlink.regCommands();
    Stage9Clean36::fileManager.regCommands();
    Stage9Clean36::health.regCommands();
    Stage9Clean36::prmDb.regCommands();
    Stage9Clean36::systemResources.regCommands();
  }

  void readParameters() {
    // Nothing to do
  }

  void loadParameters() {
    // Nothing to do
  }

  void startTasks(const TopologyState& state) {
    Stage9Clean36::blockDrv.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_blockDrv),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_blockDrv),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_blockDrv)
    );
    Stage9Clean36::cmdDisp.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_cmdDisp),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_cmdDisp),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_cmdDisp)
    );
    Stage9Clean36::cmdSeq.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_cmdSeq),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_cmdSeq),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_cmdSeq)
    );
    Stage9Clean36::comQueue.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_comQueue),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_comQueue),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_comQueue)
    );
    Stage9Clean36::eventLogger.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_eventLogger),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_eventLogger),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_eventLogger)
    );
    Stage9Clean36::fileDownlink.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_fileDownlink),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_fileDownlink),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_fileDownlink)
    );
    Stage9Clean36::fileManager.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_fileManager),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_fileManager),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_fileManager)
    );
    Stage9Clean36::fileUplink.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_fileUplink),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_fileUplink),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_fileUplink)
    );
    Stage9Clean36::prmDb.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_prmDb),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_prmDb),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_prmDb)
    );
    Stage9Clean36::rateGroup1.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_rateGroup1),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_rateGroup1),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_rateGroup1)
    );
    Stage9Clean36::rateGroup2.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_rateGroup2),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_rateGroup2),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_rateGroup2)
    );
    Stage9Clean36::rateGroup3.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_rateGroup3),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_rateGroup3),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_rateGroup3)
    );
    Stage9Clean36::tlmSend.start(
      static_cast<Os::Task::ParamType>(Priorities::Stage9Clean36_tlmSend),
      static_cast<Os::Task::ParamType>(StackSizes::Stage9Clean36_tlmSend),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::Stage9Clean36_tlmSend)
    );
  }

  void stopTasks(const TopologyState& state) {
    Stage9Clean36::blockDrv.exit();
    Stage9Clean36::cmdDisp.exit();
    Stage9Clean36::cmdSeq.exit();
    Stage9Clean36::comQueue.exit();
    Stage9Clean36::eventLogger.exit();
    Stage9Clean36::fileDownlink.exit();
    Stage9Clean36::fileManager.exit();
    Stage9Clean36::fileUplink.exit();
    Stage9Clean36::prmDb.exit();
    Stage9Clean36::rateGroup1.exit();
    Stage9Clean36::rateGroup2.exit();
    Stage9Clean36::rateGroup3.exit();
    Stage9Clean36::tlmSend.exit();
  }

  void freeThreads(const TopologyState& state) {
    (void) Stage9Clean36::blockDrv.ActiveComponentBase::join();
    (void) Stage9Clean36::cmdDisp.ActiveComponentBase::join();
    (void) Stage9Clean36::cmdSeq.ActiveComponentBase::join();
    (void) Stage9Clean36::comQueue.ActiveComponentBase::join();
    (void) Stage9Clean36::eventLogger.ActiveComponentBase::join();
    (void) Stage9Clean36::fileDownlink.ActiveComponentBase::join();
    (void) Stage9Clean36::fileManager.ActiveComponentBase::join();
    (void) Stage9Clean36::fileUplink.ActiveComponentBase::join();
    (void) Stage9Clean36::prmDb.ActiveComponentBase::join();
    (void) Stage9Clean36::rateGroup1.ActiveComponentBase::join();
    (void) Stage9Clean36::rateGroup2.ActiveComponentBase::join();
    (void) Stage9Clean36::rateGroup3.ActiveComponentBase::join();
    (void) Stage9Clean36::tlmSend.ActiveComponentBase::join();
  }

  void tearDownComponents(const TopologyState& state) {
    // Nothing to do
  }

  // ----------------------------------------------------------------------
  // Setup and teardown functions
  // ----------------------------------------------------------------------

  void setup(const TopologyState& state) {
    initComponents(state);
    configComponents(state);
    setBaseIds();
    connectComponents();
    regCommands();
    readParameters();
    loadParameters();
    startTasks(state);
  }

  void teardown(const TopologyState& state) {
    stopTasks(state);
    freeThreads(state);
    tearDownComponents(state);
  }

}
